[workspace]
resolver = "2"
members = [
  "crates/k8dnz-core",
  "crates/k8dnz-cli",
]

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
thiserror = "2"
blake3 = "1"
crc32fast = "1"
clap = { version = "4", features = ["derive"] }
anyhow = "1"
