[package]
name = "k8dnz-core"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
thiserror = { workspace = true }
blake3 = { workspace = true }
crc32fast = { workspace = true }
